language: php

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true

  global:
    - DEFAULT=1

  include:
    - php: 7.4
      env: PHPCS=1 PHPSTAN=1 DEFAULT=0

    - php: 8.0
      env: PHPCS=1 PHPSTAN=1 DEFAULT=0

before_script:
  - if [[ $DEFAULT = 1 || $PHPCS = 1 ]]; then composer install; fi
  - if [[ $DEFAULT = 1 ]]; then composer run-script post-install-cmd --no-interaction; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev "phpstan/phpstan"; fi

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/ plugins/LilExpenses/src/ plugins/LilCrm/src/ plugins/LilInvoices/src/ plugins/LilProjects/src/ plugins/Tasks/src/; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 5 src/ plugins/LilExpenses/src/ plugins/LilCrm/src/ plugins/LilInvoices/src/ plugins/LilProjects/src/ plugins/Tasks/src/; fi

notifications:
  email: false
