<?php
declare(strict_types=1);

namespace Crm\Model\Table;

use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * ContactsSearchIndex Model
 *
 * @property \Crm\Model\Table\ContactsTable&\Cake\ORM\Association\BelongsTo $Contacts
 * @method \Crm\Model\Entity\ContactsSearchIndex newEmptyEntity()
 * @method \Crm\Model\Entity\ContactsSearchIndex newEntity(array $data, array $options = [])
 * @method array<\Crm\Model\Entity\ContactsSearchIndex> newEntities(array $data, array $options = [])
 * @method \Crm\Model\Entity\ContactsSearchIndex get(mixed $primaryKey, array|string $finder = 'all', \Psr\SimpleCache\CacheInterface|string|null $cache = null, \Closure|string|null $cacheKey = null, mixed ...$args)
 * @method \Crm\Model\Entity\ContactsSearchIndex findOrCreate($search, ?callable $callback = null, array $options = [])
 * @method \Crm\Model\Entity\ContactsSearchIndex patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method array<\Crm\Model\Entity\ContactsSearchIndex> patchEntities(iterable $entities, array $data, array $options = [])
 * @method \Crm\Model\Entity\ContactsSearchIndex|false save(\Cake\Datasource\EntityInterface $entity, array $options = [])
 * @method \Crm\Model\Entity\ContactsSearchIndex saveOrFail(\Cake\Datasource\EntityInterface $entity, array $options = [])
 * @method iterable<\Crm\Model\Entity\ContactsSearchIndex>|\Cake\Datasource\ResultSetInterface<\Crm\Model\Entity\ContactsSearchIndex>|false saveMany(iterable $entities, array $options = [])
 * @method iterable<\Crm\Model\Entity\ContactsSearchIndex>|\Cake\Datasource\ResultSetInterface<\Crm\Model\Entity\ContactsSearchIndex> saveManyOrFail(iterable $entities, array $options = [])
 * @method iterable<\Crm\Model\Entity\ContactsSearchIndex>|\Cake\Datasource\ResultSetInterface<\Crm\Model\Entity\ContactsSearchIndex>|false deleteMany(iterable $entities, array $options = [])
 * @method iterable<\Crm\Model\Entity\ContactsSearchIndex>|\Cake\Datasource\ResultSetInterface<\Crm\Model\Entity\ContactsSearchIndex> deleteManyOrFail(iterable $entities, array $options = [])
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 * @extends \Cake\ORM\Table<array{}, \Crm\Model\Entity\ContactsSearchIndex>
 */
class ContactsSearchIndexTable extends Table
{
    /**
     * Initialize method
     *
     * @param array<string, mixed> $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('contacts_search_index');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Contacts', [
            'foreignKey' => 'contact_id',
            'joinType' => 'INNER',
            'className' => 'Crm.Contacts',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->uuid('contact_id')
            ->notEmptyString('contact_id');

        $validator
            ->scalar('content')
            ->allowEmptyString('content');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['contact_id'], 'Contacts'), ['errorField' => 'contact_id']);

        return $rules;
    }

    /**
     * Updates or creates the search index record for the given contact id.
     * The content is generated by concatenating the contact's first name, last name, tax number,
     * account names, addresses, emails and phones.
     *
     * @param string $contactId Contact id to update the index for.
     * @return void
     */
    public function updateContactIndex(string $contactId): void
    {
        /** @var \Crm\Model\Table\ContactsTable $ContactsTable */
        $ContactsTable = $this->getAssociation('Contacts')->getTarget();

        $contact = $ContactsTable->find()
            ->where(['Contacts.id' => $contactId])
            ->contain(['ContactsAccounts', 'ContactsAddresses', 'ContactsEmails', 'ContactsPhones'])
            ->firstOrFail();

        $data = [
            $contact->first_name,
            $contact->last_name,
            $contact->title,
            $contact->tax_no,
            $contact->mat_no,
            implode(' ', array_map(fn($a) => preg_replace('/\s+/', '', $a->iban), $contact->contacts_accounts)),
            implode(' ', array_map(
                fn($a) => implode(' ', [$a->street, $a->zip, $a->city]),
                $contact->contacts_addresses,
            )),
            implode(' ', array_map(fn($a) => $a->email, $contact->contacts_emails)),
            implode(' ', array_map(fn($a) => preg_replace('/\s+/', '', $a->no), $contact->contacts_phones)),
        ];

        $content = $this->buildSearchableTokens($data);

        /** @var \Crm\Model\Entity\ContactsSearchIndex|null $indexEntity */
        $indexEntity = $this->find()->where(['contact_id' => $contactId])->first();
        if (!$indexEntity) {
            $indexEntity = $this->newEmptyEntity();
            $indexEntity->contact_id = $contactId;
            $indexEntity->owner_id = $contact->owner_id ?? '';
        }
        $indexEntity->content = trim($content);
        $this->saveOrFail($indexEntity);
    }

    /**
     * Builds a string of searchable tokens from the given data array.
     * The tokens are generated by normalizing the input values (lowercasing, removing accents),
     * splitting into words, and generating various combinations and prefixes of the words.
     *
     * @param array<string> $data Array of input strings to generate tokens from.
     * @return string A string of unique searchable tokens separated by spaces.
     */
    private function buildSearchableTokens(array $data): string
    {
        $tokens = [];
        foreach ($data as $value) {
            if (!$value) {
                continue;
            }

            // lowercase
            $value = mb_strtolower(trim($value));

            // odstrani šumnike
            $normalized = $this->removeAccents($value);

            // original + normalized
            $variants = array_unique([$value, $normalized]);

            foreach ($variants as $text) {
                // osnovni token
                $tokens[] = $text;

                // brez posebnih znakov
                $alnum = (string)preg_replace('/[^a-z0-9]+/iu', ' ', $text);

                $tokens[] = $alnum;

                // split words
                $words = preg_split('/\s+/', $alnum) ?: [];

                $words = array_filter($words);

                // posamezne besede
                foreach ($words as $word) {
                    $tokens[] = $word;

                    // prefix search tokeni
                    // janez -> j jan jane ...
                    $len = mb_strlen($word);

                    $minLen = min($len, 10);
                    for ($i = 2; $i <= $minLen; $i++) {
                        $tokens[] = mb_substr($word, 0, $i);
                    }
                }

                // kombinacije besed
                if (count($words) > 1) {
                    // janeznovak
                    $tokens[] = implode('', $words);

                    // janez novak
                    $tokens[] = implode(' ', $words);

                    // novak janez
                    $reversed = array_reverse($words);
                    $tokens[] = implode(' ', $reversed);
                    $tokens[] = implode('', $reversed);
                }

                // telefon normalizacija
                $digits = (string)preg_replace('/\D+/', '', $text);

                if (strlen($digits) >= 3) {
                    $tokens[] = $digits;

                    // brez 386 prefixa
                    if (str_starts_with($digits, '386')) {
                        $tokens[] = substr($digits, 3);
                    }

                    // brez začetne 0
                    if (str_starts_with($digits, '0')) {
                        $tokens[] = substr($digits, 1);
                    }
                }

                // email tokeni
                if (filter_var($text, FILTER_VALIDATE_EMAIL)) {
                    $tokens[] = $text;

                    [$local, $domain] = explode('@', $text);

                    $tokens[] = $local;
                    $tokens[] = $domain;

                    $domainParts = explode('.', $domain);

                    foreach ($domainParts as $part) {
                        $tokens[] = $part;
                    }
                }
            }
        }

        // cleanup
        $tokens = array_map(fn(string $v): string => trim($v), $tokens);

        $tokens = array_unique(explode(' ', implode(' ', $tokens)));

        $tokens = array_filter($tokens, function ($v) {
            return mb_strlen($v) >= 2;
        });

        return implode(' ', $tokens);
    }

    /**
     * Removes accents from a string, replacing them with their unaccented counterparts.
     *
     * @param string $string The input string from which to remove accents.
     * @return string The input string with accents removed.
     */
    private function removeAccents(string $string): string
    {
        $map = [
            'č' => 'c',
            'ć' => 'c',
            'š' => 's',
            'ž' => 'z',
            'đ' => 'd',
            'Č' => 'c',
            'Ć' => 'c',
            'Š' => 's',
            'Ž' => 'z',
            'Đ' => 'd',
        ];

        return strtr($string, $map);
    }

    /**
     * Builds a boolean search query string for MySQL fulltext search from the given input string.
     * The input string is split into words, normalized, and transformed into a boolean search query
     * where each word is prefixed with '+' for required match and suffixed with '*' for
     * prefix matching.
     *
     * @param string $search The input search string to transform into a boolean search query.
     * @return string The transformed boolean search query string.
     */
    public function buildBooleanSearchQuery(string $search): string
    {
        $parts = preg_split('/\s+/', mb_strtolower(trim($search))) ?: [];

        $tokens = [];

        foreach ($parts as $part) {
            $part = trim($part);

            if (mb_strlen($part) < 2) {
                continue;
            }

            // odstrani posebne znake
            $part = preg_replace('/[^\pL\pN]+/u', '', $part);

            if (!$part) {
                continue;
            }

            $tokens[] = '+' . $part . '*';
        }

        return implode(' ', $tokens);
    }

    /**
     * Performs a fulltext search on the contacts search index for the given search string and owner id.
     * Returns an array of contact ids and their corresponding relevance scores, ordered by score descending.
     * The search is performed using MySQL fulltext search in boolean mode, and the search string is transformed
     * using the buildBooleanSearchQuery method to generate the appropriate query syntax.
     *
     * @param string $searchStr The input search string to search for.
     * @param string $ownerId The owner id to filter the search results by.
     * @return array<string, float> An associative array where the keys are contact ids and the values are their corresponding relevance scores.
     */
    public function search(string $searchStr, string $ownerId): array
    {
        $q = $this->find();
        /** @var array<string, float> $ret */
        $ret = $q
            ->select(['contact_id', 'score' => $q->expr('MATCH(content) AGAINST(:term IN BOOLEAN MODE)')])
            ->where(['owner_id' => $ownerId])
            ->andWhere('MATCH(content) AGAINST(:term IN BOOLEAN MODE)')
            ->bind(':term', $this->buildBooleanSearchQuery($searchStr), 'string')
            ->orderBy(['score' => 'DESC'])
            ->limit(100)
            ->all()
            ->combine('contact_id', 'score')
            ->toArray();

        return $ret;
    }
}
