<?php

    $banks = [
        '01' => ['name' => 'BANKA SLOVENIJE', 'bic' => 'BSLJSI2X'],
        '29' => ['name' => 'UNICREDIT BANKA SLOVENIJA D.D.', 'bic' => 'BACXSI22'],
        '06' => ['name' => 'BANKA CELJE D.D.', 'bic' => 'SBCESI2X'],
        '10' => ['name' => 'BANKA KOPER D.D.', 'bic' => 'BAKOSI2X'],
        '19' => ['name' => 'DEŽELNA BANKA SLOVENIJE D.D.', 'bic' => 'SZKBSI2X'],
        '27' => ['name' => 'FACTOR BANKA D.D.', 'bic' => 'FCTBSI2X'],
        '07' => ['name' => 'GORENJSKA BANKA, D.D., KRANJ', 'bic' => 'GORESI2X'],
        '33' => ['name' => 'HYPO-ALPE-ADRIA BANK D.D.', 'bic' => 'HAABSI22'],
        '34' => ['name' => 'BANKA SPARKASSE D.D.', 'bic' => 'KSPKSI22'],
        '04' => ['name' => 'NOVA KREDITNA BANKA MARIBOR D.D.', 'bic' => 'KBMASI2X'],
        '02' => ['name' => 'NOVA LJUBLJANSKA BANKA D.D.', 'bic' => 'LJBASI2X'],
        '90' => ['name' => 'POŠTNA BANKA SLOVENIJE D.D.', 'bic' => 'PBSLSI22'],
        '25' => ['name' => 'PROBANKA D.D.', 'bic' => 'PROBSI2X'],
        '24' => ['name' => 'RAIFFEISEN BANKA D.D.', 'bic' => 'KREKSI22'],
        '03' => ['name' => 'SKB BANKA D.D.', 'bic' => 'SKBASI2X'],
        '30' => ['name' => 'BANKA VOLKSBANK D.D.', 'bic' => 'SLBVSI2X'],
        '35' => ['name' => 'BKS BANK AG, BANČNA PODRUŽNICA', 'bic' => 'BFKKSI22'],
        '37' => ['name' => 'ZVEZA BANK, PODRUŽNICA LJUBLJANA', 'bic' => 'VSGKSI2K'],
        '38' => ['name' => 'SID - Slovenska izvozna in razvojna banka, d.d., Ljubljana', 'bic' => 'SIDRSI22'],
        '05' => ['name' => 'ABANKA VIPA d.d.', 'bic' => 'ABANSI2X'],
        '41' => ['name' => 'KD Banka d.d.', 'bic' => 'KDBASI22'],
        '61' => ['name' => 'DELAVSKA HRANILNICA D.D.', 'bic' => 'HDELSI22'],
        '60' => ['name' => 'HRANILNICA LON D.D. KRANJ', 'bic' => 'HLONSI22'],
        '64' => ['name' => 'HRANILNICA IN POSOJILNICA VIPAVA D.D.', 'bic' => 'HKVISI22'],
    ];
